<?php 
	$this->load->view('artefatos/site/header.php');
	$this->load->view('artefatos/site/menu.php');
	$this->load->view('site/inicial.php');
	$this->load->view('site/sobre.php');
	$this->load->view('site/pedidos.php');
	$this->load->view('site/promocoes.php');
	$this->load->view('site/cardapio.php');
	$this->load->view('site/contatos.php');
	$this->load->view('artefatos/site/footer.php');
?>